[package]
name = "newhatch-analyzer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
argon2.workspace = true
async-trait.workspace = true
axum.workspace = true
crc32fast.workspace = true
httparse.workspace = true
libc.workspace = true
newhatch-collector = { path = "../collector" }
newhatch-protocol = { path = "../protocol" }
regex.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-sessions.workspace = true
time.workspace = true
rpassword = "7.3"
rand_core = { version = "0.6", features = ["getrandom"] }
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile = "3.15"
tower = { version = "0.5", features = ["util"] }

[[test]]
name = "auth"
path = "../../test/auth/backend.rs"
